server:
  port: ${APP_PORT}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/annyamd/hs-config-repo.git
          username: ${GIT_USER}
          password: ${GIT_TOKEN}
          default-label: master
          clone-on-start: true
